### ISSUE TITLE
Bug issue with purge.js (or a suggestion)

### ISSUE THREAD

**Issue by HecksForLifw** [Zenoleader/MGS-Bot#2]
Hey MGS Bot team,

So I'm thinking that since there is a thing that checks the perms for the bot, shouldn't there be a thing where it checks for the user too? Also, you should probably add something that makes them not allow it to be empty :)

Thanks for the codes,
Hecker :)

**Comment by Zenoleader** [comment]
So we did add that feature to the normal bot right after the command was published in GitHub! We will add it ASAP. 

Thanks,
MGS Bot team
